"""DPO (Direct Preference Optimization) trainer for DHS/DocWain.

Trains the model to prefer DocWain-style responses over anti-pattern responses.
Uses TRL's DPOTrainer on preference pairs generated by dpo_data_generator.py.

Usage:
    python -m src.finetune.dpo_trainer
    python -m src.finetune.dpo_trainer --base-model path/to/sft-model --epochs 3
"""

from __future__ import annotations

import argparse
import json
import logging
import os
import sys
from pathlib import Path
from typing import Any, Dict, Optional

from src.utils.logging_utils import get_logger

log = get_logger(__name__)

# Must match the SFT base model (8B fits T4 16GB, 14B needs A100)
BASE_MODEL_ID = "unsloth/Qwen3-8B-bnb-4bit"
ARTIFACT_DIR = Path(os.getenv("DOCWAIN_HOME", ".")) / "finetune_artifacts" / "dpo"
DATASET_DIR = Path("finetune_data")
MAX_SEQ_LENGTH = 4096

SYSTEM_PROMPT = (
    "You are DocWain — Document Wise AI Node — an intelligent document intelligence "
    "platform engineered by DHS IT Solutions Ltd."
)


def run_dpo_training(
    *,
    base_model: Optional[str] = None,
    epochs: int = 3,
    learning_rate: float = 5e-5,
    lora_r: int = 16,
    beta: float = 0.1,
) -> Dict[str, Any]:
    """Run DPO training on preference pairs."""
    base_model = base_model or BASE_MODEL_ID
    ARTIFACT_DIR.mkdir(parents=True, exist_ok=True)

    # Step 1: Load dataset
    train_path = DATASET_DIR / "dpo_train.jsonl"
    eval_path = DATASET_DIR / "dpo_eval.jsonl"

    if not train_path.exists():
        log.info("Generating DPO dataset...")
        from src.finetune.dpo_data_generator import build_dpo_dataset
        build_dpo_dataset(output_dir=DATASET_DIR)

    from datasets import load_dataset
    dataset = load_dataset("json", data_files=str(train_path), split="train")
    eval_dataset = None
    if eval_path.exists():
        eval_dataset = load_dataset("json", data_files=str(eval_path), split="train")

    log.info("DPO dataset: %d train, %d eval", len(dataset), len(eval_dataset) if eval_dataset else 0)

    # Step 2: Load model
    from unsloth import FastLanguageModel

    log.info("Loading base model: %s", base_model)
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name=base_model,
        max_seq_length=MAX_SEQ_LENGTH,
        dtype=None,
        load_in_4bit=True,
    )

    model = FastLanguageModel.get_peft_model(
        model,
        r=lora_r,
        lora_alpha=lora_r * 2,
        lora_dropout=0.0,
        target_modules=["q_proj", "k_proj", "v_proj", "o_proj"],
        bias="none",
        use_gradient_checkpointing="unsloth",
    )

    # Step 3: Format dataset for DPO
    def format_for_dpo(example):
        prompt = example["prompt"]
        chosen = example["chosen"]
        rejected = example["rejected"]

        # Format as Qwen3 chat messages
        prompt_formatted = (
            f"<|im_start|>system\n{SYSTEM_PROMPT}<|im_end|>\n"
            f"<|im_start|>user\n{prompt}<|im_end|>\n"
            f"<|im_start|>assistant\n"
        )
        return {
            "prompt": prompt_formatted,
            "chosen": chosen + "<|im_end|>\n",
            "rejected": rejected + "<|im_end|>\n",
        }

    dataset = dataset.map(format_for_dpo)
    if eval_dataset:
        eval_dataset = eval_dataset.map(format_for_dpo)

    # Step 4: Training
    from transformers import TrainingArguments
    from trl import DPOTrainer, DPOConfig

    output_dir = ARTIFACT_DIR / "checkpoints"
    output_dir.mkdir(parents=True, exist_ok=True)

    try:
        # TRL >= 0.9 uses DPOConfig
        training_args = DPOConfig(
            output_dir=str(output_dir),
            per_device_train_batch_size=1,
            gradient_accumulation_steps=8,
            learning_rate=learning_rate,
            num_train_epochs=epochs,
            warmup_steps=5,
            logging_steps=1,
            save_strategy="epoch",
            beta=beta,
            fp16=True,
            report_to="none",
            seed=42,
            max_length=MAX_SEQ_LENGTH,
            max_prompt_length=MAX_SEQ_LENGTH // 2,
        )
    except (TypeError, ImportError):
        # Fallback for older TRL versions
        training_args = TrainingArguments(
            output_dir=str(output_dir),
            per_device_train_batch_size=1,
            gradient_accumulation_steps=8,
            learning_rate=learning_rate,
            num_train_epochs=epochs,
            warmup_steps=5,
            logging_steps=1,
            save_strategy="epoch",
            fp16=True,
            report_to="none",
            seed=42,
        )

    trainer = DPOTrainer(
        model=model,
        ref_model=None,  # Use implicit reference model (PEFT)
        args=training_args,
        train_dataset=dataset,
        eval_dataset=eval_dataset,
        tokenizer=tokenizer,
    )

    log.info("Starting DPO training (%d examples, %d epochs, lr=%.2e, beta=%.2f)...",
             len(dataset), epochs, learning_rate, beta)
    train_result = trainer.train()

    final_loss = train_result.metrics.get("train_loss", 0.0)
    log.info("DPO training complete (loss=%.4f)", final_loss)

    # Step 5: Save merged model
    merged_dir = ARTIFACT_DIR / "merged"
    merged_dir.mkdir(parents=True, exist_ok=True)

    try:
        model.save_pretrained_merged(str(merged_dir), tokenizer, save_method="merged_16bit")
    except AttributeError:
        model.save_pretrained(str(merged_dir))
        tokenizer.save_pretrained(str(merged_dir))

    summary = {
        "train_loss": final_loss,
        "epochs": epochs,
        "learning_rate": learning_rate,
        "lora_r": lora_r,
        "beta": beta,
        "train_examples": len(dataset),
    }
    with open(ARTIFACT_DIR / "training_summary.json", "w") as f:
        json.dump(summary, f, indent=2)

    return summary


def main():
    parser = argparse.ArgumentParser(description="DPO training for DHS/DocWain")
    parser.add_argument("--base-model", type=str, default=BASE_MODEL_ID)
    parser.add_argument("--epochs", type=int, default=3)
    parser.add_argument("--lr", type=float, default=5e-5)
    parser.add_argument("--lora-r", type=int, default=16)
    parser.add_argument("--beta", type=float, default=0.1)
    args = parser.parse_args()

    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s [%(name)s] %(message)s")

    result = run_dpo_training(
        base_model=args.base_model,
        epochs=args.epochs,
        learning_rate=args.lr,
        lora_r=args.lora_r,
        beta=args.beta,
    )
    print(f"\nDPO Training Complete: {json.dumps(result, indent=2)}")


if __name__ == "__main__":
    sys.exit(main())
