"""Document pipeline status constants."""

# Top-level pipeline statuses
PIPELINE_UPLOADED = "UPLOADED"
PIPELINE_EXTRACTION_IN_PROGRESS = "EXTRACTION_IN_PROGRESS"
PIPELINE_EXTRACTION_COMPLETED = "EXTRACTION_COMPLETED"
PIPELINE_EXTRACTION_FAILED = "EXTRACTION_FAILED"
PIPELINE_SCREENING_IN_PROGRESS = "SCREENING_IN_PROGRESS"
PIPELINE_SCREENING_COMPLETED = "SCREENING_COMPLETED"
PIPELINE_SCREENING_FAILED = "SCREENING_FAILED"
PIPELINE_EMBEDDING_IN_PROGRESS = "EMBEDDING_IN_PROGRESS"
PIPELINE_TRAINING_COMPLETED = "TRAINING_COMPLETED"
PIPELINE_EMBEDDING_FAILED = "EMBEDDING_FAILED"

# Per-stage statuses
STAGE_PENDING = "PENDING"
STAGE_IN_PROGRESS = "IN_PROGRESS"
STAGE_COMPLETED = "COMPLETED"
STAGE_FAILED = "FAILED"

# KG statuses (independent of pipeline)
KG_PENDING = "PENDING"
KG_IN_PROGRESS = "IN_PROGRESS"
KG_COMPLETED = "COMPLETED"
KG_FAILED = "FAILED"

# Legacy mappings (for backward compatibility during migration)
# NOTE: STATUS_UNDER_REVIEW must keep its original literal value because
# existing documents in MongoDB have status="UNDER_REVIEW" (not "UPLOADED").
STATUS_UNDER_REVIEW = "UNDER_REVIEW"
STATUS_TRAINING_STARTED = PIPELINE_EMBEDDING_IN_PROGRESS
STATUS_TRAINING_SUCCEEDED = PIPELINE_TRAINING_COMPLETED
STATUS_TRAINING_FAILED = PIPELINE_EMBEDDING_FAILED
STATUS_EXTRACTION_COMPLETED = PIPELINE_EXTRACTION_COMPLETED
STATUS_SCREENING_COMPLETED = PIPELINE_SCREENING_COMPLETED

# Additional legacy constants (preserved for backward compatibility)
STATUS_EXTRACTION_FAILED = "EXTRACTION_FAILED"
STATUS_EXTRACTION_OR_CHUNKING_FAILED = "EXTRACTION_OR_CHUNKING_FAILED"
STATUS_EMBEDDING_COMPLETED = "EMBEDDING_COMPLETED"
STATUS_EMBEDDING_FAILED = "EMBEDDING_FAILED"
STATUS_FAILED = "FAILED"
STATUS_TRAINING_COMPLETED = PIPELINE_TRAINING_COMPLETED
STATUS_TRAINING_PARTIALLY_COMPLETED = "TRAINING_PARTIALLY_COMPLETED"
STATUS_TRAINING_BLOCKED_SECURITY = "TRAINING_BLOCKED_SECURITY"
STATUS_TRAINING_BLOCKED_CONFIDENTIAL = "TRAINING_BLOCKED_CONFIDENTIAL"
STATUS_DELETED = "DELETED"

ALL_STATUSES = {
    STATUS_EXTRACTION_COMPLETED,
    STATUS_EXTRACTION_FAILED,
    STATUS_EXTRACTION_OR_CHUNKING_FAILED,
    STATUS_SCREENING_COMPLETED,
    STATUS_EMBEDDING_COMPLETED,
    STATUS_EMBEDDING_FAILED,
    STATUS_FAILED,
    STATUS_UNDER_REVIEW,
    STATUS_TRAINING_STARTED,
    STATUS_TRAINING_COMPLETED,
    STATUS_TRAINING_PARTIALLY_COMPLETED,
    STATUS_TRAINING_FAILED,
    STATUS_TRAINING_BLOCKED_SECURITY,
    STATUS_TRAINING_BLOCKED_CONFIDENTIAL,
    STATUS_DELETED,
}
