"""Shared document status constants."""

STATUS_EXTRACTION_COMPLETED = "EXTRACTION_COMPLETED"
STATUS_EXTRACTION_FAILED = "EXTRACTION_FAILED"
STATUS_EXTRACTION_OR_CHUNKING_FAILED = "EXTRACTION_OR_CHUNKING_FAILED"
STATUS_SCREENING_COMPLETED = "SCREENING_COMPLETED"
STATUS_EMBEDDING_COMPLETED = "EMBEDDING_COMPLETED"
STATUS_EMBEDDING_FAILED = "EMBEDDING_FAILED"
STATUS_FAILED = "FAILED"

STATUS_UNDER_REVIEW = "UNDER_REVIEW"
STATUS_TRAINING_STARTED = "TRAINING_STARTED"
STATUS_TRAINING_COMPLETED = "TRAINING_COMPLETED"
STATUS_TRAINING_PARTIALLY_COMPLETED = "TRAINING_PARTIALLY_COMPLETED"
STATUS_TRAINING_FAILED = "TRAINING_FAILED"
STATUS_TRAINING_BLOCKED_SECURITY = "TRAINING_BLOCKED_SECURITY"
STATUS_TRAINING_BLOCKED_CONFIDENTIAL = "TRAINING_BLOCKED_CONFIDENTIAL"
STATUS_DELETED = "DELETED"

ALL_STATUSES = {
    STATUS_EXTRACTION_COMPLETED,
    STATUS_EXTRACTION_FAILED,
    STATUS_EXTRACTION_OR_CHUNKING_FAILED,
    STATUS_SCREENING_COMPLETED,
    STATUS_EMBEDDING_COMPLETED,
    STATUS_EMBEDDING_FAILED,
    STATUS_FAILED,
    STATUS_UNDER_REVIEW,
    STATUS_TRAINING_STARTED,
    STATUS_TRAINING_COMPLETED,
    STATUS_TRAINING_PARTIALLY_COMPLETED,
    STATUS_TRAINING_FAILED,
    STATUS_TRAINING_BLOCKED_SECURITY,
    STATUS_TRAINING_BLOCKED_CONFIDENTIAL,
    STATUS_DELETED,
}
